### ISSUE TITLE
"This repository is over its data quota. Purchase more data packs to restore access."

### ISSUE THREAD

**Issue by JaMesLiMers** [calvozaragoza/tf-deep-omr#1]
Hi,
I am a student who interested about the omr project and I am unable to pull .meta data from Github because of git-lfs quota.

these are the issue code:
`git lfs clone https://github.com/calvozaragoza/tf-deep-omr.git
Cloning into 'tf-deep-omr'...
remote: Counting objects: 100, done.
remote: Total 100 (delta 0), reused 0 (delta 0), pack-reused 100
Receiving objects: 100% (100/100), 305.23 KiB | 0 bytes/s, done.
Resolving deltas: 100% (48/48), done.
Checking connectivity... done.
batch response: This repository is over its data quota. Purchase more data packs to restore access.                                                                               
error: failed to fetch some objects from 'https://github.com/calvozaragoza/tf-deep-omr.git/info/lfs'`

According to following article, the same git-lfs assets are used across public repositories, which means that our fork is also unavailable, and we are using your bandwidth.
I thought I was partly responsible, and I was happy to pay for next month for it.

The link: https://help.github.com/articles/purchasing-additional-storage-and-bandwidth-for-a-personal-account/

**Comment by apacha** [comment]
It would actually be better to not store the models inside the source-code, but as a dedicated binary, attached to a release (see: https://github.com/apacha/MusicObjectDetector-TF/releases/tag/full-page-detection-v2)

**Comment by JaMesLiMers** [comment]
> It would actually be better to not store the models inside the source-code, but as a dedicated binary, attached to a release (see: https://github.com/apacha/MusicObjectDetector-TF/releases/tag/full-page-detection-v2)

Thank you so much!

**Comment by JaMesLiMers** [comment]
@apacha 
Thank you for the advice !
