### ISSUE TITLE
About Training Dataset

### ISSUE THREAD

**Issue by thuhuwei** [calvozaragoza/tf-deep-omr#5]
Thanks for this work. And which dataset is employed to train two provided models, the original PrIMuS or Camera PrIMuS ?

**Comment by calvozaragoza** [comment]
Hi,

The provided models were trained with PrIMuS, but the scripts can be executed for training with Camera-PrIMuS.

**Comment by thuhuwei** [comment]
Thanks. Another question: Do you consider to support multiple-voice polyphonic staves in near future?

**Comment by calvozaragoza** [comment]
Of course, that's an ongoing line of research but I don't know when I might get some results.
