### ISSUE TITLE
How could I convert the predict-result to midi/mxml?

### ISSUE THREAD

**Issue by magneter** [calvozaragoza/tf-deep-omr#6]
HI ,it is a great job.
But I do not konw how could I convet the result to midi /mxml.
Could you please give me some advices?
Thanks

**Comment by calvozaragoza** [comment]
Hi,

I'm afraid we are not providing that functionality in this repository. However, you can take a look to the last section of this site: https://grfia.dlsi.ua.es/primus/ , where a tool for converting the **semantic output** to a midi file is provided. 

That tool has not been extensively tested, so I cannot assure it will work in all cases.
