### ISSUE TITLE
prlMus dataset

### ISSUE THREAD

**Issue by trungpham2606** [calvozaragoza/tf-deep-omr#8]
Hello calvozaragoza,
I just downloaded the prlmus dataset from the webpage you had provided. 
But I wonder how can I read this file because it has unknown file type.

**Comment by calvozaragoza** [comment]
The dataset is compressed as a tgz file. There are many ways to uncompress, for instance using 7zip (https://www.7-zip.org/)

**Comment by trungpham2606** [comment]
@calvozaragoza oh tks a lots for figuring me out ^^
